<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;


class RnkController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionAlign()
    {
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $seq1 = $post['seq1'];
            $seq2 = $post['seq2'];

            $position = strpos($seq1, $seq2);

            $result = [
                'message' => $position ? 'Matches were found!' : 'No matches found',
                'position' => $position
            ];
        }
        return $this->render('align', [
            'result' => $result ?? ['message'=>'', 'position' =>''],
            'seq1' => $seq1 ?? '',
            'seq2' => $seq2 ?? '',
        ]);
    }

    public function actionDownload()
    {

        $ch = curl_init();
        $source = "https://blast.ncbi.nlm.nih.gov/BlastAlign.cgi?RID=CDAJP1FP113&FORMAT_TYPE=JSON2&CMD=GET";
        curl_setopt($ch, CURLOPT_URL, $source);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $data = curl_exec ($ch);
        curl_close ($ch);

        $destination = "file.zip";
        $file = fopen($destination, "w+");
        fputs($file, $data);
        fclose($file);

        return 0;
    }


}
